### ISSUE TITLE
gateway临时存储功能

### ISSUE THREAD

**Issue by modeyang** [open-falcon/gateway#1]
如果遇到中心与中心之间网络抖动，导致无法正常发送，gateway模块是否可以支持临时存储，待网络通后将数据再批量发送给核心中间的transfer集群。
是否有打算？ 或者提供些许机制解决此种问题？ 谢谢。

**Comment by niean** [comment]
现有数据存储方案，不支持补发数据。所以，你的提议不容易实现。

过时的数据，对实时报警无意义，对于历史绘图意义也不太大。

聂安

**Comment by modeyang** [comment]
谢谢，不过历史数据有时需要进行数据统计用，补全了数据才好统计。

**Comment by laiwei** [comment]
@modeyang 

gateway、agent 后续都会考虑，当网络中断时，数据首先落地，待故障恢复后再行传输的工作。

不过具体的设计，还没有仔细讨论。

有进度我会随时在这里update，谢谢

**Comment by modeyang** [comment]
好的，谢谢。
